package main

import (
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// sirBinaryPath is the resolved absolute path to the sir binary.
// Set once at startup by resolveSirBinary(). Tests override this to a
// fixed value so hook commands are predictable regardless of test-binary path.
var sirBinaryPath string

func init() {
	sirBinaryPath = resolveSirBinaryPath()
}

// resolveSirBinaryPath returns the absolute path to the sir binary.
// This is critical for security: hook commands must use an absolute path
// to prevent $PATH hijacking (an agent could place a malicious "sir" binary
// in a writable PATH directory and intercept all hook invocations).
// Falls back to exec.LookPath if os.Executable fails. Returns "sir" as last resort.
func resolveSirBinaryPath() string {
	if exePath, err := os.Executable(); err == nil {
		if resolved, err := filepath.EvalSymlinks(exePath); err == nil {
			return resolved
		}
		return exePath
	}
	if lookPath, err := exec.LookPath("sir"); err == nil {
		if resolved, err := filepath.Abs(lookPath); err == nil {
			return resolved
		}
		return lookPath
	}
	return "sir"
}

// isSirHookCommand returns true if cmd is a sir hook command.
// Matches commands generated by generateHooksConfig: "<sirBinaryPath> guard <subcommand>".
func isSirHookCommand(cmd string) bool {
	return strings.Contains(cmd, sirBinaryPath+" guard ")
}
