// Code generated by scripts/generate_protocol_wire.py; DO NOT EDIT.

package core

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"

	"github.com/somoore/sir/pkg/policy"
)

const (
	protocolMagic          = "MSTR"
	protocolVersion byte   = 0x01
	maxFrameBytes   uint32 = 10 * 1024 * 1024
)

type wireEvalRequest struct {
	Verb                 string  `json:"verb"`
	Target               string  `json:"target"`
	ToolName             string  `json:"tool_name"`
	Labels               []Label `json:"labels"`
	DerivedLabels        []Label `json:"derived_labels"`
	SessionSecret        bool    `json:"session_secret"`
	SessionUntrustedRead bool    `json:"session_untrusted_read"`
	IsPostureFile        bool    `json:"is_posture_file"`
	IsSensitivePath      bool    `json:"is_sensitive_path"`
	IsDelegation         bool    `json:"is_delegation"`
	IsTripwire           bool    `json:"is_tripwire"`
}

type wireEvalResponse struct {
	Verdict       policy.Verdict `json:"verdict"`
	Reason        string         `json:"reason"`
	RiskTier      string         `json:"risk_tier"`
	LabelsApplied []Label        `json:"labels_applied"`
	ReceiptId     string         `json:"receipt_id"`
	Timestamp     uint64         `json:"timestamp"`
}

type wireSessionPayload struct {
	SecretSession         bool   `json:"secret_session"`
	RecentlyReadUntrusted bool   `json:"recently_read_untrusted"`
	DenyAll               bool   `json:"deny_all"`
	ApprovalScope         string `json:"approval_scope"`
	TurnCounter           uint64 `json:"turn_counter"`
}

type wireRequestEnvelope struct {
	Request wireEvalRequest    `json:"request"`
	Session wireSessionPayload `json:"session"`
	Lease   json.RawMessage    `json:"lease,omitempty"`
}

func buildWireEvalRequest(req *Request) wireEvalRequest {
	return wireEvalRequest{
		Verb:                 req.Intent.Verb.String(),
		Target:               req.Intent.Target,
		ToolName:             req.ToolName,
		Labels:               nonNilLabels(req.Intent.Labels),
		DerivedLabels:        nonNilLabels(req.Intent.DerivedLabels),
		SessionSecret:        req.Session.SecretSession,
		SessionUntrustedRead: req.Session.RecentlyReadUntrusted,
		IsPostureFile:        req.Intent.IsPosture,
		IsSensitivePath:      req.Intent.IsSensitive,
		IsDelegation:         req.Intent.IsDelegation,
		IsTripwire:           req.Intent.IsTripwire,
	}
}

func buildWireSessionPayload(req *Request) wireSessionPayload {
	return wireSessionPayload{
		SecretSession:         req.Session.SecretSession,
		RecentlyReadUntrusted: req.Session.RecentlyReadUntrusted,
		DenyAll:               req.Session.DenyAll,
		ApprovalScope:         req.Session.ApprovalScope,
		TurnCounter:           uint64(req.Session.TurnCounter),
	}
}

func buildWireRequestEnvelope(req *Request) wireRequestEnvelope {
	envelope := wireRequestEnvelope{
		Request: buildWireEvalRequest(req),
		Session: buildWireSessionPayload(req),
	}
	if len(req.LeaseJSON) > 0 && json.Valid(req.LeaseJSON) {
		envelope.Lease = append(json.RawMessage(nil), req.LeaseJSON...)
	}
	return envelope
}

func encodeMSTR1(req *Request) ([]byte, error) {
	payloadJSON, err := json.Marshal(buildWireRequestEnvelope(req))
	if err != nil {
		return nil, err
	}
	return encodeFrame(payloadJSON), nil
}

func decodeMSTR1Response(data []byte) (*Response, error) {
	payload, err := decodeFrame(data)
	if err != nil {
		return nil, err
	}
	return decodeWireEvalResponse(payload)
}

func decodeWireEvalResponse(payload []byte) (*Response, error) {
	var wireResp wireEvalResponse
	if err := json.Unmarshal(payload, &wireResp); err != nil {
		return nil, err
	}
	return &Response{
		Decision: wireResp.Verdict,
		Reason:   wireResp.Reason,
		Risk:     wireResp.RiskTier,
	}, nil
}

func encodeFrame(payload []byte) []byte {
	var buf bytes.Buffer
	buf.WriteString(protocolMagic)
	buf.WriteByte(protocolVersion)
	var payloadLen [4]byte
	binary.BigEndian.PutUint32(payloadLen[:], uint32(len(payload)))
	buf.Write(payloadLen[:])
	buf.Write(payload)
	return buf.Bytes()
}

func decodeFrame(data []byte) ([]byte, error) {
	if len(data) < 9 {
		return nil, fmt.Errorf("response too short: %d bytes", len(data))
	}
	if string(data[0:4]) != protocolMagic {
		return nil, fmt.Errorf("invalid MSTR/1 magic in response")
	}
	if data[4] != protocolVersion {
		return nil, fmt.Errorf("unsupported MSTR/1 version: %d", data[4])
	}
	length := binary.BigEndian.Uint32(data[5:9])
	if length > maxFrameBytes {
		return nil, fmt.Errorf("frame too large: %d bytes (max %d)", length, maxFrameBytes)
	}
	if int(length) > len(data)-9 {
		return nil, fmt.Errorf("response length mismatch: declared %d, available %d", length, len(data)-9)
	}
	return data[9 : 9+length], nil
}
