#!/usr/bin/env python3

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "mister-shared" / "policy_surface.json"
GO_OUT = ROOT / "pkg" / "policy" / "surface_gen.go"


def load_spec():
    with SPEC_PATH.open("r", encoding="utf-8") as f:
        return json.load(f)


def emit_string_type(type_name, const_prefix, values):
    lines = [f"type {type_name} string", "", "const ("]
    for item in values:
        line = f'\t{const_prefix}{item["name"]} {type_name} = "{item["wire"]}"'
        if type_name == "Verb" and "credential" in item["wire"]:
            line += " // #nosec G101 -- generated verb identifier, not a credential"
        lines.append(line)
    lines.append(")")
    lines.append("")
    lines.append(f"var All{type_name}s = []{type_name}{{")
    for item in values:
        lines.append(f"\t{const_prefix}{item['name']},")
    lines.append("}")
    lines.append("")
    lines.append(f"func (v {type_name}) String() string {{")
    lines.append("\treturn string(v)")
    lines.append("}")
    lines.append("")
    lines.append(f"func Parse{type_name}(s string) ({type_name}, bool) {{")
    lines.append(f"\tv := {type_name}(s)")
    lines.append("\tswitch v {")
    case_values = ", ".join(f"{const_prefix}{item['name']}" for item in values)
    lines.append(f"\tcase {case_values}:")
    lines.append("\t\treturn v, true")
    lines.append("\tdefault:")
    lines.append("\t\treturn " + type_name + "(\"\"), false")
    lines.append("\t}")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main():
    spec = load_spec()
    parts = [
        "// Code generated by scripts/generate_policy_surface.py; DO NOT EDIT.",
        "",
        "package policy",
        "",
        emit_string_type("Verb", "Verb", spec["verbs"]),
        emit_string_type("Verdict", "Verdict", spec["verdicts"]),
        emit_string_type("PostureState", "PostureState", spec["posture_states"]),
        emit_string_type("ApprovalScope", "ApprovalScope", spec["approval_scopes"]),
        f"const SessionSchemaVersion uint32 = {spec['session_schema_version']}",
        "",
    ]
    GO_OUT.parent.mkdir(parents=True, exist_ok=True)
    GO_OUT.write_text("\n".join(parts), encoding="utf-8")


if __name__ == "__main__":
    main()
