// Code generated by scripts/generate_policy_surface.py; DO NOT EDIT.

package policy

type Verb string

const (
	VerbNetLocal Verb = "net_local"
	VerbNetAllowlisted Verb = "net_allowlisted"
	VerbNetExternal Verb = "net_external"
	VerbPushOrigin Verb = "push_origin"
	VerbPushRemote Verb = "push_remote"
	VerbRunEphemeral Verb = "run_ephemeral"
	VerbReadRef Verb = "read_ref"
	VerbStageWrite Verb = "stage_write"
	VerbExecuteDryRun Verb = "execute_dry_run"
	VerbRunTests Verb = "run_tests"
	VerbCommit Verb = "commit"
	VerbListFiles Verb = "list_files"
	VerbSearchCode Verb = "search_code"
	VerbEnvRead Verb = "env_read"
	VerbDnsLookup Verb = "dns_lookup"
	VerbPersistence Verb = "persistence"
	VerbSudo Verb = "sudo"
	VerbDeletePosture Verb = "delete_posture"
	VerbDelegate Verb = "delegate"
	VerbMcpUnapproved Verb = "mcp_unapproved"
	VerbMcpCredentialLeak Verb = "mcp_credential_leak" // #nosec G101 -- generated verb identifier, not a credential
	VerbMcpInjectionDetected Verb = "mcp_injection_detected"
	VerbCredentialDetected Verb = "credential_detected" // #nosec G101 -- generated verb identifier, not a credential
	VerbElicitationHarvest Verb = "elicitation_harvest"
	VerbSirSelf Verb = "sir_self"
)

var AllVerbs = []Verb{
	VerbNetLocal,
	VerbNetAllowlisted,
	VerbNetExternal,
	VerbPushOrigin,
	VerbPushRemote,
	VerbRunEphemeral,
	VerbReadRef,
	VerbStageWrite,
	VerbExecuteDryRun,
	VerbRunTests,
	VerbCommit,
	VerbListFiles,
	VerbSearchCode,
	VerbEnvRead,
	VerbDnsLookup,
	VerbPersistence,
	VerbSudo,
	VerbDeletePosture,
	VerbDelegate,
	VerbMcpUnapproved,
	VerbMcpCredentialLeak,
	VerbMcpInjectionDetected,
	VerbCredentialDetected,
	VerbElicitationHarvest,
	VerbSirSelf,
}

func (v Verb) String() string {
	return string(v)
}

func ParseVerb(s string) (Verb, bool) {
	v := Verb(s)
	switch v {
	case VerbNetLocal, VerbNetAllowlisted, VerbNetExternal, VerbPushOrigin, VerbPushRemote, VerbRunEphemeral, VerbReadRef, VerbStageWrite, VerbExecuteDryRun, VerbRunTests, VerbCommit, VerbListFiles, VerbSearchCode, VerbEnvRead, VerbDnsLookup, VerbPersistence, VerbSudo, VerbDeletePosture, VerbDelegate, VerbMcpUnapproved, VerbMcpCredentialLeak, VerbMcpInjectionDetected, VerbCredentialDetected, VerbElicitationHarvest, VerbSirSelf:
		return v, true
	default:
		return Verb(""), false
	}
}

type Verdict string

const (
	VerdictAllow Verdict = "allow"
	VerdictDeny Verdict = "deny"
	VerdictAsk Verdict = "ask"
)

var AllVerdicts = []Verdict{
	VerdictAllow,
	VerdictDeny,
	VerdictAsk,
}

func (v Verdict) String() string {
	return string(v)
}

func ParseVerdict(s string) (Verdict, bool) {
	v := Verdict(s)
	switch v {
	case VerdictAllow, VerdictDeny, VerdictAsk:
		return v, true
	default:
		return Verdict(""), false
	}
}

type PostureState string

const (
	PostureStateNormal PostureState = "normal"
	PostureStateElevated PostureState = "elevated"
	PostureStateCritical PostureState = "critical"
)

var AllPostureStates = []PostureState{
	PostureStateNormal,
	PostureStateElevated,
	PostureStateCritical,
}

func (v PostureState) String() string {
	return string(v)
}

func ParsePostureState(s string) (PostureState, bool) {
	v := PostureState(s)
	switch v {
	case PostureStateNormal, PostureStateElevated, PostureStateCritical:
		return v, true
	default:
		return PostureState(""), false
	}
}

type ApprovalScope string

const (
	ApprovalScopeSession ApprovalScope = "session"
	ApprovalScopeTurn ApprovalScope = "turn"
)

var AllApprovalScopes = []ApprovalScope{
	ApprovalScopeSession,
	ApprovalScopeTurn,
}

func (v ApprovalScope) String() string {
	return string(v)
}

func ParseApprovalScope(s string) (ApprovalScope, bool) {
	v := ApprovalScope(s)
	switch v {
	case ApprovalScopeSession, ApprovalScopeTurn:
		return v, true
	default:
		return ApprovalScope(""), false
	}
}

const SessionSchemaVersion uint32 = 1
